/** Body position data for Tai Chi step diagrams (100×100 viewBox). */

export interface PosePoint {
  x: number;
  y: number;
}

export interface TaiChiBodyPose {
  id: string;
  /** Short caption under the figure */
  caption: string;
  head: PosePoint;
  shoulder: PosePoint;
  leftHand: PosePoint;
  rightHand: PosePoint;
  hip: PosePoint;
  leftFoot: PosePoint;
  rightFoot: PosePoint;
  leftKnee?: PosePoint;
  rightKnee?: PosePoint;
  weight?: "left" | "right" | "center";
}

export const TAI_CHI_POSES: Record<string, TaiChiBodyPose> = {
  "stand-neutral": {
    id: "stand-neutral",
    caption: "Stand tall",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 38, y: 48 },
    rightHand: { x: 62, y: 48 },
    hip: { x: 50, y: 52 },
    leftKnee: { x: 44, y: 68 },
    rightKnee: { x: 56, y: 68 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "stand-relaxed": {
    id: "stand-relaxed",
    caption: "Shoulders soft",
    head: { x: 50, y: 15 },
    shoulder: { x: 50, y: 28 },
    leftHand: { x: 36, y: 52 },
    rightHand: { x: 64, y: 52 },
    hip: { x: 50, y: 54 },
    leftKnee: { x: 44, y: 70 },
    rightKnee: { x: 56, y: 70 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "arms-down": {
    id: "arms-down",
    caption: "Arms resting",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 34, y: 58 },
    rightHand: { x: 66, y: 58 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "arms-raised": {
    id: "arms-raised",
    caption: "Raise the sun",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 32, y: 18 },
    rightHand: { x: 68, y: 18 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "palms-down": {
    id: "palms-down",
    caption: "Palms turn down",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 30, y: 38 },
    rightHand: { x: 70, y: 38 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "cloud-left": {
    id: "cloud-left",
    caption: "Weight left, arms right",
    head: { x: 46, y: 14 },
    shoulder: { x: 46, y: 26 },
    leftHand: { x: 58, y: 32 },
    rightHand: { x: 78, y: 40 },
    hip: { x: 44, y: 52 },
    leftFoot: { x: 38, y: 88 },
    rightFoot: { x: 54, y: 88 },
    weight: "left",
  },
  "cloud-right": {
    id: "cloud-right",
    caption: "Weight right, arms left",
    head: { x: 54, y: 14 },
    shoulder: { x: 54, y: 26 },
    leftHand: { x: 22, y: 40 },
    rightHand: { x: 42, y: 32 },
    hip: { x: 56, y: 52 },
    leftFoot: { x: 46, y: 88 },
    rightFoot: { x: 62, y: 88 },
    weight: "right",
  },
  "brush-left": {
    id: "brush-left",
    caption: "Brush back (left)",
    head: { x: 48, y: 14 },
    shoulder: { x: 48, y: 26 },
    leftHand: { x: 68, y: 36 },
    rightHand: { x: 24, y: 50 },
    hip: { x: 48, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "brush-right": {
    id: "brush-right",
    caption: "Brush back (right)",
    head: { x: 52, y: 14 },
    shoulder: { x: 52, y: 26 },
    leftHand: { x: 76, y: 50 },
    rightHand: { x: 32, y: 36 },
    hip: { x: 52, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "hands-belly": {
    id: "hands-belly",
    caption: "Hands at belly",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 44, y: 56 },
    rightHand: { x: 56, y: 56 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "ground-feet": {
    id: "ground-feet",
    caption: "Feel your feet",
    head: { x: 50, y: 15 },
    shoulder: { x: 50, y: 28 },
    leftHand: { x: 38, y: 54 },
    rightHand: { x: 62, y: 54 },
    hip: { x: 50, y: 54 },
    leftFoot: { x: 40, y: 88 },
    rightFoot: { x: 60, y: 88 },
    weight: "center",
  },
  "wave-low": {
    id: "wave-low",
    caption: "Arms ripple low",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 28, y: 62 },
    rightHand: { x: 72, y: 62 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "wave-high": {
    id: "wave-high",
    caption: "Arms ripple high",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 22, y: 28 },
    rightHand: { x: 78, y: 28 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "hold-ball": {
    id: "hold-ball",
    caption: "Cup the orb",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 40, y: 42 },
    rightHand: { x: 60, y: 42 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "shift-left-ball": {
    id: "shift-left-ball",
    caption: "Shift left, orb centered",
    head: { x: 46, y: 14 },
    shoulder: { x: 46, y: 26 },
    leftHand: { x: 38, y: 42 },
    rightHand: { x: 58, y: 42 },
    hip: { x: 44, y: 52 },
    leftFoot: { x: 36, y: 88 },
    rightFoot: { x: 54, y: 88 },
    weight: "left",
  },
  "press-down": {
    id: "press-down",
    caption: "Press palms down",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 38, y: 62 },
    rightHand: { x: 62, y: 62 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "meadow-root": {
    id: "meadow-root",
    caption: "Root in meadow",
    head: { x: 50, y: 15 },
    shoulder: { x: 50, y: 28 },
    leftHand: { x: 36, y: 50 },
    rightHand: { x: 64, y: 50 },
    hip: { x: 50, y: 54 },
    leftFoot: { x: 40, y: 88 },
    rightFoot: { x: 60, y: 88 },
    weight: "center",
  },
  "gate-open-left": {
    id: "gate-open-left",
    caption: "Step out left, arms wide",
    head: { x: 44, y: 14 },
    shoulder: { x: 44, y: 26 },
    leftHand: { x: 18, y: 34 },
    rightHand: { x: 72, y: 34 },
    hip: { x: 42, y: 52 },
    leftFoot: { x: 28, y: 88 },
    rightFoot: { x: 52, y: 88 },
    weight: "left",
  },
  "gate-center": {
    id: "gate-center",
    caption: "Return to center",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 32, y: 40 },
    rightHand: { x: 68, y: 40 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "repulse-left": {
    id: "repulse-left",
    caption: "Push left, weight back",
    head: { x: 48, y: 14 },
    shoulder: { x: 48, y: 26 },
    leftHand: { x: 20, y: 44 },
    rightHand: { x: 58, y: 52 },
    hip: { x: 52, y: 52 },
    leftFoot: { x: 48, y: 88 },
    rightFoot: { x: 64, y: 88 },
    weight: "right",
  },
  "repulse-right": {
    id: "repulse-right",
    caption: "Push right, weight back",
    head: { x: 52, y: 14 },
    shoulder: { x: 52, y: 26 },
    leftHand: { x: 42, y: 52 },
    rightHand: { x: 80, y: 44 },
    hip: { x: 48, y: 52 },
    leftFoot: { x: 36, y: 88 },
    rightFoot: { x: 52, y: 88 },
    weight: "left",
  },
  "gather-in": {
    id: "gather-in",
    caption: "Gather inward",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 44, y: 46 },
    rightHand: { x: 56, y: 46 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "gather-out": {
    id: "gather-out",
    caption: "Expand outward",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 22, y: 38 },
    rightHand: { x: 78, y: 38 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "hands-heart": {
    id: "hands-heart",
    caption: "Hands at heart",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 44, y: 40 },
    rightHand: { x: 56, y: 40 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "float-stance": {
    id: "float-stance",
    caption: "Soft knees, float",
    head: { x: 50, y: 15 },
    shoulder: { x: 50, y: 28 },
    leftHand: { x: 36, y: 48 },
    rightHand: { x: 64, y: 48 },
    hip: { x: 50, y: 56 },
    leftKnee: { x: 42, y: 72 },
    rightKnee: { x: 58, y: 72 },
    leftFoot: { x: 40, y: 88 },
    rightFoot: { x: 60, y: 88 },
    weight: "center",
  },
  "rooster-left": {
    id: "rooster-left",
    caption: "Left knee lifts",
    head: { x: 48, y: 14 },
    shoulder: { x: 48, y: 26 },
    leftHand: { x: 36, y: 36 },
    rightHand: { x: 64, y: 36 },
    hip: { x: 50, y: 52 },
    leftKnee: { x: 38, y: 62 },
    rightFoot: { x: 58, y: 88 },
    leftFoot: { x: 38, y: 72 },
    weight: "right",
  },
  "rooster-right": {
    id: "rooster-right",
    caption: "Right knee lifts",
    head: { x: 52, y: 14 },
    shoulder: { x: 52, y: 26 },
    leftHand: { x: 36, y: 36 },
    rightHand: { x: 64, y: 36 },
    hip: { x: 50, y: 52 },
    rightKnee: { x: 62, y: 62 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 62, y: 72 },
    weight: "left",
  },
  "wave-rider-left": {
    id: "wave-rider-left",
    caption: "Shift left, arms follow",
    head: { x: 44, y: 14 },
    shoulder: { x: 44, y: 26 },
    leftHand: { x: 26, y: 44 },
    rightHand: { x: 58, y: 50 },
    hip: { x: 42, y: 52 },
    leftFoot: { x: 34, y: 88 },
    rightFoot: { x: 54, y: 88 },
    weight: "left",
  },
  "wave-rider-right": {
    id: "wave-rider-right",
    caption: "Shift right, arms follow",
    head: { x: 56, y: 14 },
    shoulder: { x: 56, y: 26 },
    leftHand: { x: 42, y: 50 },
    rightHand: { x: 74, y: 44 },
    hip: { x: 58, y: 52 },
    leftFoot: { x: 46, y: 88 },
    rightFoot: { x: 66, y: 88 },
    weight: "right",
  },
  "palms-up": {
    id: "palms-up",
    caption: "Palms up at sides",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 28, y: 52 },
    rightHand: { x: 72, y: 52 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
  "palms-rest": {
    id: "palms-rest",
    caption: "Palms down to rest",
    head: { x: 50, y: 14 },
    shoulder: { x: 50, y: 26 },
    leftHand: { x: 38, y: 58 },
    rightHand: { x: 62, y: 58 },
    hip: { x: 50, y: 52 },
    leftFoot: { x: 42, y: 88 },
    rightFoot: { x: 58, y: 88 },
    weight: "center",
  },
};

export function getTaiChiPose(id: string): TaiChiBodyPose | undefined {
  return TAI_CHI_POSES[id];
}