export interface Category {
  slug: string;
  title: string;
  description: string;
  image?: string;
  keywords?: string;
}

export const categories: Category[] = [
  { slug: 'business', title: 'Grok for Business', description: 'Practical prompts for meetings, strategy, research, content and operations.', image: '/images/grok-for-business-2026.jpg' },
  { slug: 'marketing', title: 'Grok for Marketing', description: 'Content, social, email, SEO & campaign prompts using real-time signals.', image: '/images/grok-for-marketing-2026.jpg' },
  { slug: 'sales', title: 'Grok for Sales', description: 'Outreach, account research, proposals and objection handling.', image: '/images/grok-for-sales-2026.jpg' },
  { slug: 'engineers', title: 'Grok for Engineers', description: 'Code review, system design, debugging and learning new tech.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'entrepreneurs', title: 'Grok for Entrepreneurs', description: 'Idea validation, pitch decks, fundraising and growth experiments.', image: '/images/grok-for-entrepreneurs-2026.jpg' },
  { slug: 'students', title: 'Grok for Students', description: 'Study aids, essays, research, exam prep and time management.', image: '/images/grok-for-students-2026.jpg' },
  { slug: 'teachers', title: 'Grok for Teachers', description: 'Lesson planning, differentiation and parent communications.', image: '/images/grok-for-teachers-2026.jpg' },
  { slug: 'product-managers', title: 'Grok for Product Managers', description: 'PRDs, roadmaps, user research and stakeholder updates.', image: '/images/grok-for-product-managers-2026.jpg' },
  { slug: 'data-analysts', title: 'Grok for Data Analysts', description: 'Data cleaning, visualization, dashboards and storytelling.', image: '/images/grok-for-data-analysts-2026.jpg' },
  { slug: 'copywriters', title: 'Grok for Copywriters', description: 'Headlines, long-form, emails and brand voice content.', image: '/images/grok-for-copywriters-2026.jpg' },
  { slug: 'hr', title: 'Grok for HR', description: 'Job descriptions, interviews, onboarding and performance reviews.', image: '/images/grok-for-hr-2026.jpg' },
  { slug: 'lawyers', title: 'Grok for Lawyers', description: 'Contract review, legal research and case strategy.', image: '/images/grok-for-lawyers-2026.jpg' },
  { slug: 'real-estate', title: 'Grok for Real Estate', description: 'Listings, market analysis, client scripts and negotiations.', image: '/images/grok-for-real-estate-2026.jpg' },
  { slug: 'musicians', title: 'Grok for Musicians & Writers', description: 'Lyrics, song ideas, bios and creative block breaking.', image: '/images/grok-for-musicians-2026.jpg' },
  { slug: 'assistants', title: 'Grok for Assistants & Secretaries', description: 'Administrative work, emails, calendars and research.', image: '/images/grok-for-assistants-secretaries-2026.jpg' },
  { slug: 'healthcare', title: 'Grok for Healthcare Professionals', description: 'Patient communication, research, documentation and wellness prompts.', image: '/images/grok-for-healthcare-2026.jpg' },
  { slug: 'investors', title: 'Grok for Investors and Traders', description: 'Market analysis, due diligence, portfolio strategy using real-time signals.', image: '/images/grok-for-investors-2026.jpg' },
  { slug: 'fitness', title: 'Grok for Fitness, Health and Nutrition', description: 'Workout plans, meal prep, habit building and wellness coaching.', image: '/images/grok-for-fitness-health-2026.jpg' },
  { slug: 'productivity', title: 'Grok for Productivity', description: 'Task management, focus techniques, automation and daily systems.', image: '/images/grok-50-best-prompts.jpg' },
  { slug: 'creative-writing', title: 'Grok for Creative Writing', description: 'Story development, character creation, worldbuilding and editing.', image: '/images/grok-prompt-engineering-masterclass-2026.jpg' },
  { slug: 'social-media', title: 'Grok for Social Media Managers', description: 'Content calendars, viral hooks, community engagement and analytics.', image: '/images/grok-for-marketing-2026.jpg' },
  { slug: 'video-creators', title: 'Grok for Video Creators and YouTubers', description: 'Script writing, thumbnails, titles, SEO and video concepts.', image: '/images/grok-for-video-creators-2026.jpg' },
  { slug: 'language-learners', title: 'Grok for Language Learners', description: 'Conversation practice, vocabulary, grammar, and cultural immersion prompts.', image: '/images/grok-for-language-learners-2026.jpg' },
  { slug: 'travel-planners', title: 'Grok for Travel Planning and Itineraries', description: 'Itinerary building, destination research, booking tips, and packing lists.', image: '/images/grok-for-travel-planners-2026.jpg' },
  { slug: 'market-research', title: 'Grok for Market Research and Analysis', description: 'Survey design, trend spotting, competitor analysis, and insight synthesis.', image: '/images/grok-for-market-research-2026.jpg' },
  { slug: 'customer-support', title: 'Grok for Customer Support and Service', description: 'Ticket handling, empathy scripting, escalation playbooks, and knowledge base creation.', image: '/images/grok-for-customer-support-2026.jpg' },
  { slug: 'personal-finance', title: 'Grok for Personal Finance and Budgeting', description: 'Budgeting, investing basics, debt management, and financial planning.', image: '/images/grok-for-personal-finance-2026.jpg' },
  { slug: 'dating-relationships', title: 'Grok for Dating and Relationships', description: 'Conversation starters, conflict resolution, date planning, and communication scripts.', image: '/images/grok-50-best-prompts.jpg' },
  { slug: 'parenting-family', title: 'Grok for Parenting and Family', description: 'Parenting tips, family activities, discipline strategies, and communication.', image: '/images/grok-50-best-prompts.jpg' },
  { slug: 'pet-care', title: 'Grok for Pet Care and Training', description: 'Pet training, health advice, behavior issues, and enrichment ideas.', image: '/images/grok-for-healthcare-2026.jpg' },
  { slug: 'gardening-diy', title: 'Grok for Gardening and Home DIY', description: 'Plant care, garden planning, home improvement projects, and repairs.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'sustainability', title: 'Grok for Sustainability and ESG', description: 'Sustainable living, ESG strategies, green initiatives, and impact measurement.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'nonprofits', title: 'Grok for Non-profits and Charity', description: 'Fundraising, volunteer management, grant writing, and impact reporting.', image: '/images/grok-for-business-2026.jpg' },
  { slug: 'consulting', title: 'Grok for Consulting and Freelancing', description: 'Client deliverables, proposal writing, workshop design, and stakeholder mapping.', image: '/images/grok-for-product-managers-2026.jpg' },
  { slug: 'cloud-devops', title: 'Grok for Cloud Computing and DevOps', description: 'Infrastructure, deployment, monitoring, IaC, and incident response.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'machine-learning', title: 'Grok for Machine Learning and AI Ethics', description: 'Model development, data pipelines, bias detection, and responsible AI.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'event-planning', title: 'Grok for Event and Wedding Planning', description: 'Timeline building, vendor negotiation, run-of-show, and contingency planning.', image: '/images/grok-50-best-prompts.jpg' },
  { slug: 'music-production', title: 'Grok for Music Production', description: 'Beat making, mixing, mastering, sound design, and artist collaboration.', image: '/images/grok-for-musicians-2026.jpg' },
  { slug: 'ecommerce', title: 'Grok for E-commerce and Online Business', description: 'Product descriptions, email/SMS flows, upsell, pricing tests, and storefront optimization.', image: '/images/grok-for-marketing-2026.jpg' },
  { slug: 'grant-writing', title: 'Grok for Grant Writing', description: 'Proposal structure, needs statements, budgets, and impact metrics.', image: '/images/grok-for-copywriters-2026.jpg' },
  { slug: 'competitive-intelligence', title: 'Grok for Competitive Intelligence', description: 'Real-time competitor monitoring, SWOT, pricing moves, and market positioning.', image: '/images/grok-search-research-guide-2026.jpg' },
  { slug: 'risk-management', title: 'Grok for Risk Management', description: 'Risk assessment, mitigation plans, compliance, and crisis response.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'team-collaboration', title: 'Grok for Team Collaboration', description: 'Meeting facilitation, project alignment, feedback frameworks, and async communication.', image: '/images/grok-for-business-2026.jpg' },
  { slug: 'leadership', title: 'Grok for Leadership', description: 'Vision setting, team motivation, decision frameworks, and executive presence.', image: '/images/grok-for-business-2026.jpg' },
  { slug: 'fashion-style', title: 'Grok for Fashion and Style', description: 'Trend analysis, outfit curation, personal styling, and brand voice.', image: '/images/grok-50-best-prompts.jpg' },
  { slug: 'history-philosophy', title: 'Grok for History and Philosophy', description: 'Historical analysis, philosophical debates, and contextual insights.', image: '/images/grok-search-research-guide-2026.jpg' },
  { slug: 'astronomy', title: 'Grok for Astronomy and Space', description: 'Celestial events, space exploration, astrophysics explanations, and stargazing.', image: '/images/grok-prompt-engineering-masterclass-2026.jpg' },
  { slug: 'mental-health', title: 'Grok for Mental Health and Wellness', description: 'Self-care strategies, mindfulness, emotional intelligence, and coping tools.', image: '/images/grok-for-healthcare-2026.jpg' },
  { slug: 'automotive', title: 'Grok for Automotive', description: 'Vehicle maintenance, buying guides, modifications, and automotive tech.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'sports', title: 'Grok for Sports Coaching', description: 'Training plans, game strategy, player development, and performance analysis.', image: '/images/grok-50-best-prompts.jpg' },
  { slug: 'ar-vr', title: 'Grok for AR/VR and Metaverse', description: 'Experience design, worldbuilding, user interaction, and immersive content.', image: '/images/grok-for-video-creators-2026.jpg' },
  { slug: 'robotics', title: 'Grok for Robotics', description: 'Robot design, programming, automation workflows, and ethical considerations.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'quantum', title: 'Grok for Quantum Computing', description: 'Quantum algorithms, qubit concepts, and applications in computing.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'web3-crypto', title: 'Grok for Web3 and Crypto', description: 'Blockchain, DeFi, NFT strategy, tokenomics, and on-chain analysis.', image: '/images/grok-search-research-guide-2026.jpg' },

  // Additions to ensure at least 2 categories per letter A-Z
  { slug: 'blogging', title: 'Grok for Blogging', description: 'Content creation, audience engagement, SEO for blogs, and consistent posting strategies.', image: '/images/grok-50-best-prompts.jpg' },
  { slug: 'branding', title: 'Grok for Branding', description: 'Brand voice development, visual identity, storytelling, and market positioning.', image: '/images/grok-for-marketing-2026.jpg' },
  { slug: 'influencers', title: 'Grok for Influencers', description: 'Content ideas, audience growth, collaboration pitches, and brand partnerships.', image: '/images/grok-for-video-creators-2026.jpg' },
  { slug: 'it-security', title: 'Grok for IT Security', description: 'Threat analysis, compliance, incident response, and security best practices.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'journalists', title: 'Grok for Journalists', description: 'Story research, interview prep, fact-checking, and article outlining.', image: '/images/grok-search-research-guide-2026.jpg' },
  { slug: 'job-seekers', title: 'Grok for Job Seekers', description: 'Resume writing, interview preparation, networking strategies, and career pivots.', image: '/images/grok-for-students-2026.jpg' },
  { slug: 'keynote-speakers', title: 'Grok for Keynote Speakers', description: 'Speech writing, audience engagement, storytelling, and presentation tips.', image: '/images/grok-50-best-prompts.jpg' },
  { slug: 'knowledge-management', title: 'Grok for Knowledge Management', description: 'Documentation, knowledge sharing, training materials, and organizational learning.', image: '/images/grok-for-assistants-secretaries-2026.jpg' },
  { slug: 'nursing', title: 'Grok for Nursing', description: 'Patient care protocols, documentation, continuing education, and wellness tips.', image: '/images/grok-for-healthcare-2026.jpg' },
  { slug: 'networking', title: 'Grok for Networking', description: 'Professional connections, event strategies, follow-up emails, and relationship building.', image: '/images/grok-for-business-2026.jpg' },
  { slug: 'operations', title: 'Grok for Operations', description: 'Process optimization, supply chain, efficiency improvements, and team coordination.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'outreach', title: 'Grok for Outreach', description: 'Community engagement, partnership development, email campaigns, and relationship management.', image: '/images/grok-for-marketing-2026.jpg' },
  { slug: 'quality-assurance', title: 'Grok for Quality Assurance', description: 'Testing strategies, bug reporting, process improvement, and compliance checks.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'quantitative-analysis', title: 'Grok for Quantitative Analysis', description: 'Data modeling, statistical analysis, forecasting, and financial modeling.', image: '/images/grok-for-data-analysts-2026.jpg' },
  { slug: 'ux-design', title: 'Grok for UX Design', description: 'User research, wireframing, usability testing, and interface improvements.', image: '/images/grok-for-product-managers-2026.jpg' },
  { slug: 'underwriting', title: 'Grok for Underwriting', description: 'Risk assessment, policy analysis, data evaluation, and decision support.', image: '/images/grok-for-investors-2026.jpg' },
  { slug: 'veterinarians', title: 'Grok for Veterinarians', description: 'Animal health diagnostics, treatment plans, client communication, and practice management.', image: '/images/grok-for-healthcare-2026.jpg' },
  { slug: 'videography', title: 'Grok for Videography', description: 'Video production, editing techniques, storytelling, and client projects.', image: '/images/grok-for-video-creators-2026.jpg' },
  { slug: 'web-design', title: 'Grok for Web Design', description: 'UI/UX for web, responsive design, SEO integration, and client briefs.', image: '/images/grok-for-product-managers-2026.jpg' },
  { slug: 'websites', title: 'Grok for Websites', description: 'Plan, design, code, and launch full websites and web apps. Prompts for architecture, frontend, backend, SEO, and deployment.', image: '/images/grok-prompt-engineering-masterclass-2026.jpg' },
  { slug: 'writing-coaches', title: 'Grok for Writing Coaches', description: 'Feedback on writing, curriculum development, client workshops, and publishing advice.', image: '/images/grok-50-best-prompts.jpg' },
  { slug: 'x-strategy', title: 'Grok for X Strategy', description: 'Platform-specific content, engagement tactics, analytics, and growth on X.', image: '/images/grok-search-research-guide-2026.jpg' },
  { slug: 'x-analytics', title: 'Grok for X Analytics', description: 'Data analysis on X, trend monitoring, performance metrics, and reporting.', image: '/images/grok-for-data-analysts-2026.jpg' },
  { slug: 'youth-development', title: 'Grok for Youth Development', description: 'Program design for youth, mentoring, educational activities, and engagement strategies.', image: '/images/grok-for-teachers-2026.jpg' },
  { slug: 'yoga-instructors', title: 'Grok for Yoga Instructors', description: 'Class planning, sequence design, client modifications, and studio business tips.', image: '/images/grok-for-fitness-health-2026.jpg' },
  { slug: 'zero-trust', title: 'Grok for Zero Trust Security', description: 'Security frameworks, implementation guides, compliance, and risk mitigation.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'zero-waste', title: 'Grok for Zero Waste Initiatives', description: 'Sustainability planning, waste reduction strategies, community programs, and reporting.', image: '/images/grok-for-engineers-2026.jpg' },
  { slug: 'zero-click-threats', title: 'Grok for Zero-Click Threats', description: 'Detect, prevent, and respond to zero-click attacks with Grok prompts to keep your devices and data safe.', image: '/images/grok-for-engineers-2026.jpg' },

  // Fun & creative meme/humor focused categories
  { slug: 'ultimate-meme-machine', title: 'Grok for Ultimate Meme Machine', description: 'Generate viral memes, perfect captions, formats, and unhinged humor that actually slaps.', image: '/images/grok-meme-unhinged.jpg' },
  { slug: 'savage-roasts', title: 'Grok for Savage Roasts', description: 'Craft clever, brutal, and hilarious roasts and comebacks with Grok\'s signature wit.', image: '/images/grok-meme-roast-mad.jpg' },
  { slug: 'story-mode-activated', title: 'Grok for Story Mode Activated', description: 'Dive into immersive storytelling, wild narratives, adventures, and choose-your-own chaos with Grok.', image: '/images/grok-story-mode-rapunzel.jpg' },
  { slug: 'wild-image-ideas', title: 'Grok for Wild Image Ideas', description: 'Unleash absurd, hilarious, surreal, and completely unhinged image generation prompts.', image: '/images/grok-meme-image-prompts.jpg' },
];

export function getCategoryBySlug(slug: string) {
  return categories.find(c => c.slug === slug);
}
